name: ciudadaniadigital
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.5+39

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #  json_annotation:
  #  json_model:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: ^0.5.12
  flutter_secure_storage: ^3.3.5
  flutter_appauth: ^0.9.2+6
  fluttertoast: ^7.1.1
  flutter_map: ^0.10.1+1
  geolocator: ^6.1.4
  latlong: ^0.6.1
  connectivity: ^2.0.0
  progress_dialog: ^1.2.1
  recase: ^3.0.0
  settings_ui: ^0.4.0
  flutter_slidable: ^0.5.5
  modal_bottom_sheet: ^0.2.2
  trust_fall: ^1.0.4
  flutter_jailbreak_detection: ^1.4.0
  step_progress_indicator: ^0.2.4+7
  pinput: ^0.2.6
  permission_handler: ^5.0.1+1


  webview_flutter: ^0.3.24
  flutter_inappwebview: ^4.0.0+4
  flutter_html: ^1.0.2
  open_file: ^3.0.3
  path_provider: ^1.6.22

  # Use with the CupertinoIcons class for iOS style icons.
  device_info: ^0.4.2+8
  countdown: ^0.1.0

  intl: ^0.16.1
  material_segmented_control: ^2.1.0
  flutter_datetime_picker: ^1.3.8
  sms_otp_auto_verify: ^1.2.2
  dart_otp: ^1.3.0
  flt_telephony_info: ^0.1.3
  base32: ^1.1.1
  percent_indicator: ^2.1.8
  data_connection_checker: ^0.3.4
  url_launcher: ^5.7.8
  socket_io_client: ^0.9.10
  open_mail_app: ^0.0.2
  uni_links: ^0.4.0
  package_info: ^0.4.0+13
  http: ^0.12.1
  list_tile_more_customizable: ^1.3.0
  flutter_device_type: ^0.2.0
  # ssl_pinning_plugin: ^1.3.0
  zxcvbn: ^0.0.1
  image_picker: ^0.6.7+11
  camera: ^0.5.8+11
  lzstring: ^1.0.2+1
  image: ^2.1.17
  mqtt_client: 5.6.3 # no cambiar version!
  http2_client: ^1.0.2
  # flutter_svg: ^0.18.0 # no cambiar version
  stack_trace: ^1.9.5
  flutter_local_notifications: ^3.0.1+2
  rxdart: ^0.24.1
  get_it: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  flutter_launcher_icons: "^0.8.1"

flutter_icons:
  android: true
  image_path_android: "assets/images/Logo.jpg"
  adaptive_icon_background: "assets/images/Logo.jpg"
  adaptive_icon_foreground: "assets/images/Logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat/Montserrat-Regular.otf
          weight: 900
        - asset: assets/font/Montserrat/Montserrat-Italic.otf
          weight: 800
        - asset: assets/font/Montserrat/Montserrat-Bold.otf
          weight: 700
        - asset: assets/font/Montserrat/Montserrat-SemiBold.otf
          weight: 500
        - asset: assets/font/Montserrat/Montserrat-Medium.otf
          weight: 300
        - asset: assets/font/Montserrat/Montserrat-Light.otf
          weight: 100
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Regular.ttf
          weight: 900
        - asset: assets/font/Poppins/Poppins-BoldItalic.ttf
          weight: 800
        - asset: assets/font/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/font/Poppins/Poppins-Medium.ttf
          weight: 300
        - asset: assets/font/Poppins/Poppins-Light.ttf
          weight: 100

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/tramites/
    - assets/images/buzon/
    - assets/raw/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
